# Watchdog Monitor driver
obj-$(CONFIG_APPWD) += wdm.o

# Watchdog Device driver
obj-$(CONFIG_APPWD) += wdd.o

# Watchdog Timer drivers
obj-$(CONFIG_APPWD_WDT_MPC8xxx) += wdt_mpc8xxx.o
obj-$(CONFIG_APPWD_WDT_GPIO) += wdt_gpio.o
